# @format

name: Test and Publish

on:
    # Trigger the workflow every time you push to the `main` branch
    # Using a different branch name? Replace `main` with your branch’s name
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
    contents: write
    pages: write
    id-token: write

env:
    NODE_VERSION: 24
    PNPM_VERSION: 10.22.0

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Check Licenses
              run: npx license-checker --out ./public/downloads/licenses.csv --csv --onlyAllow "0BSD;BSD-2-Clause;BSD-3-Clause;CC-BY-4.0;ISC;MIT;Apache-2.0;UNLICENSED"

            - name: Install pnpm
              uses: pnpm/action-setup@v5
              with:
                  version: ${{ env.PNPM_VERSION }}
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v5
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Type Generation
              run: pnpm types

            - name: Spell Check
              run: pnpm spell

            - name: Run Tests
              run: pnpm test

            - name: Publish if version has been updated
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
              run: |
                  PACKAGE_NAME=$(node -p "require('./package.json').name")
                  LOCAL_VERSION=$(node -p "require('./package.json').version")
                  REMOTE_VERSION=$(npm view $PACKAGE_NAME version || echo "0.0.0")

                  if [ "$LOCAL_VERSION" != "$REMOTE_VERSION" ] && [ "$(printf '%s\n%s' "$REMOTE_VERSION" "$LOCAL_VERSION" | sort -V | tail -n1)" = "$LOCAL_VERSION" ]; then
                    echo "Local version $LOCAL_VERSION is higher than remote version $REMOTE_VERSION. Publishing..."
                    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
                    npm publish --access public
                  else
                    echo "Version $LOCAL_VERSION is not newer than $REMOTE_VERSION. Skipping publish."
                  fi